### ISSUE TITLE
When releases fail slack gets notified like they didn't fail except for a tiny ❌

### ISSUE THREAD

**Issue by wadewilliams** [gundotio/release-builder#2]
The small :cross: (Is that even an emoji in most slack channels? is it custom?) is great but It's non-obvious to regular users that the release failed. 

Perhaps what is better is not spamming the channel if release fails? 

Perhaps mentioning that we are releasing :buffering: followed by success/fail: followed by gifs: followed by release notes ✅ is best.

Also this creates confusion/contention on re-runs where not spamming the channel before the release is successful is likely much better

**Comment by stevelacey** [comment]
I've swapped out the custom slack emoji defaults to stock emoji that'll work for everyone, then [overridden them in our projects](https://github.com/gundotio/worf/blob/12632dd61c143ad1cae9f3bfb4973e1561d9ffeb/.github/workflows/release-builder.yml#L54-L55) via [organization vars](https://github.com/organizations/gundotio/settings/variables/actions) to keep them rad 🤪

The simplest thing to reduce spam would be not to send the images on a retry, though I'm not sure that github exposes that it's a retry via any mechanism.

We could skip images on a `force deploy`, though not all release build retries are force deploy, even less so now we have composite actions, so maybe this doesn't help enough.

Maybe this warrants its own `silent` or `quiet` bool input, and skip all messaging in that case.

Another idea could be to store the `message-id` we already use to edit the message to mark it as 🚀/❌ as an artifact or variable somewhere, and then use that on retries to update the last message rather than send a new one.

**Comment by wadewilliams** [comment]
I think a simple ordering change could fix, 

1. @username is attempting to release new version :buffering:
2. If fail, say it failed @mention
3. If pass, gif bomb + release notes


That seems clean and would allow for multiple retries without polluting the channel
